controllers/DevController.php
<?php
namespace app_starter\controllers;

use Yii;
use app_starter\models\Dev;
use app_starter\models\DevExtend;
use app_starter\models\DevChild;
use yii\widgets\ActiveForm;

/**
 * DevController implements an highly advanced CRUD actions for Dev model.
 */
class DevController extends \technosmart\yii\web\Controller
{
    protected function findModel($id)
    {
        if (($model = Dev::find()->where(['id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new \yii\web\HttpException(404, 'The requested page does not exist.');
        }
    }

    protected function findModelChild($id)
    {
        if (($model = DevChild::find()->where(['id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new \yii\web\HttpException(404, 'The requested page does not exist.');
        }
    }
    
    public function actionDatatables()
    {
        $query = new \yii\db\Query();
        $query
            ->select([
                'd.id',
                'd.id_combination',
                'd.id_user_defined',
                'dco.name AS link',
                'de.extend AS extend',
            ])
            ->from('dev d')
            ->join('LEFT JOIN', 'dev_category_option dco', 'dco.id = d.link')
            ->join('LEFT JOIN', 'dev_extend de', 'de.id_dev = d.id')
        ;
        
        return $this->datatables($query, Yii::$app->request->post(), Dev::getDb());
    }

    public function actionDatatable()
    {
        $db = Dev::getDb();
        $post = Yii::$app->request->post();

        // serve data for datatables
        if (isset($post['draw'])) {
            $query = new \yii\db\Query();
            $query
                ->select('count(*)')
                ->from('dev d')
                ->join('LEFT JOIN', 'dev_category_option dco', 'dco.id = d.link')
                ->join('LEFT JOIN', 'dev_extend de', 'de.id_dev = d.id');
            $countWhere = count($query->where);

            $total = $query->scalar($db);
            $return['recordsTotal'] = $total;
            $return['recordsFiltered'] = $total;

            $allWhere = ['or'];
            $allSearch = $post['search']['value'];
            foreach ($post['columns'] as $key => $value) {
                if ($value['searchable'] == 'true') {
                    $column = $value['data'];
                    if (is_array($column)) {
                        if ( isset($column['filter']) )
                            $column = $column['filter'];
                        else
                            $column = $column['_'];
                    }

                    if ($value['search']['regex'] == 'false') {
                        $query->andFilterWhere(['like', $column, $value['search']['value']]);
                    } else if ($value['search']['regex'] == 'true') {
                        $query->andFilterWhere(['regexp', $column, $value['search']['value']]);
                    }

                    if ($allSearch) {
                        if ($post['search']['regex'] == 'false') {
                            $allWhere[] = ['like', $column, $allSearch];
                        } else if ($post['search']['regex'] == 'true') {
                            $allWhere[] = ['regexp', $column, $allSearch];
                        }
                    }
                }
            }
            if (count($allWhere) > 1)
                $query->andFilterWhere($allWhere);
            if (count($query->where) > $countWhere)
                $return['recordsFiltered'] = $query->scalar($db);

            $query->select([
                'd.id',
                'd.id_combination',
                'd.id_user_defined',
                'dco.name AS link',
                'de.extend AS extend',
            ]);

            $order = [];
            if (isset($post['order'])) {
                foreach ($post['order'] as $key => $value) {
                    $column = $post['columns'][$value['column']]['data'];
                    if ($post['columns'][$value['column']]['orderable'] == 'false') {
                        continue;
                    }
                    if (is_array($column)) {
                        if ( isset($column['sort']) )
                            $column = $column['sort'];
                        else
                            $column = $column['_'];
                    }

                    if ($value['dir'] == 'asc')
                        $order[$column] = SORT_ASC;
                    else if ($value['dir'] == 'desc')
                        $order[$column] = SORT_DESC;
                }
            }
            count($order) ? $query->orderBy($order) : 0;

            if (isset($post['length']))
                $query->limit(intval($post['length']));

            if (isset($post['start']))
                $query->offset(intval($post['start']));

            $return['draw'] = intval($post['draw']);
            $return['data'] = $query->all($db);
            return $this->json($return);
        }
    }

    public function actionIndex($id = null)
    {
        if (!$id) {
            return $this->render('list', [
                'title' => 'List of Datas',
            ]);
        }

        $model['dev'] = $this->findModel($id);
        return $this->render('detail', [
            'model' => $model,
            'title' => 'Detail of ' . $model['dev']->id_combination,
        ]);
    }

    public function actionCreate()
    {
        $error = true;

        $model['dev'] = isset($id) ? $this->findModel($id) : new Dev();
        $model['dev_extend'] = isset($model['dev']->devExtend) ? $model['dev']->devExtend : new DevExtend();

        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();

            $model['dev']->load($post);
            $model['dev_extend']->load($post);
            if (isset($post['DevChild'])) {
                foreach ($post['DevChild'] as $key => $value) {
                    if ($value['id'] > 0) {
                        $devChild = $this->findModelChild($value['id']);
                        $devChild->setAttributes($value);
                    } else if($value['id'] < 0) {
                        $devChild = $this->findModelChild(($value['id']*-1));
                        $devChild->isDeleted = true;
                    } else {
                        $devChild = new DevChild();
                        $devChild->setAttributes($value);
                    }
                    $model['dev_child'][] = $devChild;
                }
            }

            if (Yii::$app->request->isAjax && isset($post['ajax'])) {
                $result = array_merge(
                    ActiveForm::validate($model['dev']),
                    ActiveForm::validate($model['dev_extend'])
                );
                return $this->json($result);
            }

            $transaction['dev'] = Dev::getDb()->beginTransaction();

            try {
                if (!$model['dev']->save()) {
                    throw new \yii\web\HttpException(400, 'Data cannot be saved because there is an error in form validation. Please fix the error before submitting the form.');
                }
                
                $model['dev_extend']->id_dev = $model['dev']->id;
                if (!$model['dev_extend']->save()) {
                    throw new \yii\web\HttpException(400, 'Data cannot be saved because there is an error in form validation. Please fix the error before submitting the form.');
                }

                $error = false;

                if (isset($model['dev_child']) and is_array($model['dev_child'])) {
                    foreach ($model['dev_child'] as $key => $devChild) {
                        $devChild->id_dev = $model['dev']->id;
                        if (!$devChild->isDeleted && !$devChild->validate()) $error = true;
                    }

                    if ($error) {
                        throw new \yii\web\HttpException(400, 'Data cannot be saved because there is an error in form validation. Please fix the error before submitting the form.');
                    }
                
                    foreach ($model['dev_child'] as $key => $devChild) {
                        if ($devChild->isDeleted) {
                            if (!$devChild->delete()) {
                                $error = true;
                            }
                        } else {
                            if (!$devChild->save()) {
                                $error = true;
                            }
                        }
                    }
                }

                if ($error) {
                    throw new \yii\web\HttpException(400, 'Data cannot be saved because there is an error in form validation. Please fix the error before submitting the form.');
                }

                $transaction['dev']->commit();
                Yii::$app->session->setFlash('success', 'Data has been saved.');
            } catch (\Throwable $e) {
                $error = true;
                $transaction['dev']->rollBack();
                if (get_class($e) == 'yii\web\HttpException') Yii::$app->session->setFlash('error', $e->getMessage()); else throw $e;
            }
        } else {
            foreach ($model['dev']->devChildren as $key => $devChild)
                $model['dev_child'][] = $devChild;

            if ($model['dev']->isNewRecord) {
                $model['dev']->id_combination = $this->sequence('dev-id_combination');
                $model['dev_child'][] = new DevChild();
            }
        }

        if ($error)
            return $this->render('form', [
                'model' => $model,
                'title' => 'Create New Data',
            ]);
        else
            return $this->redirect(['index']);
    }

    public function actionUpdate($id)
    {
        $error = true;

controllers/PostController.php
<?php
namespace app_starter\controllers;

use Yii;
use technosmart\yii\web\Controller;
use app_starter\models\Post;

class PostController extends Controller
{
    /*public function actionCreatedAt()
    {
        $model['post'] = Post::find()->where(['category' => 'Health'])->andWhere(['>=', 'id', '2071'])->indexBy('id')->orderBy(['id' => SORT_ASC])->all();

        $begin = \DateTime::createFromFormat('d/m/Y', '22/11/2018');
        $end = \DateTime::createFromFormat('d/m/Y', '30/01/2020');
        $range = \DateInterval::createFromDateString('1 day');
        $allInterval = new \DatePeriod($begin, $range, $end->modify('+1 day'));

        if (ob_get_level() == 0) ob_start();
        $i = 2071;
        foreach ($allInterval as $date) {
            $nowDate = $date->format('Y-m-d');
            $nextDate = $date->modify('+1 day')->format('Y-m-d');

            $rand_epoch = rand(strtotime($nowDate), strtotime($nextDate));
            $model['post'][$i]->created_at = date('Y-m-d H:i:s', $rand_epoch);
            $model['post'][$i]->save();
            echo $i . '<br>';
            ob_flush(); flush();
            $i++;
            
            $rand_epoch = rand(strtotime($nowDate), strtotime($nextDate));
            $model['post'][$i]->created_at = date('Y-m-d H:i:s', $rand_epoch);
            $model['post'][$i]->save();
            echo $i . '<br>';
            ob_flush(); flush();
            $i++;

            $rand_epoch = rand(strtotime($nowDate), strtotime($nextDate));
            $model['post'][$i]->created_at = date('Y-m-d H:i:s', $rand_epoch);
            $model['post'][$i]->save();
            echo $i . '<br>';
            ob_flush(); flush();
            $i++;
        }
        echo 'selesai';
        ob_end_flush();
        return 0;
    }*/

    public function actionImage($t = 'brokoli.jpg')
    {
        $name = '../other/img/post/' . $t;
        try {
            $fp = fopen($name, 'rb');
            header("Content-Type: image/png");
            header("Content-Length: " . filesize($name));

            return fpassthru($fp);
        } catch (\Throwable $e) {
            throw new \yii\web\HttpException(404, 'The requested page does not exist.');
        }
    }

    public function actionIndex($t)
    {
        if (($model['post'] = Post::find()->where(['t' => $t, 'status' => 'Sedang Aktif'])->one()) == null) {
            throw new \yii\web\HttpException(404, 'The requested page does not exist.');
        }
        $model['related_post'] = Post::find()
            ->select(['id', 't', 'title', 'featured_image', 'featured_image_relative', 'created_at', 'updated_at'])
            ->where(['id' => Post::getRelatedPosts($model['post']->id), 'status' => 'Sedang Aktif'])
            ->all();
        return $this->render('detail', [
            'title' => $model['post']->title,
            'description' => $model['post']->description,
            'model' => $model,
        ]);
    }
    
    public function actionHealth($page = 1)
    {
        $model['post'] = Post::find()
            ->select(['id', 't', 'title', 'featured_image', 'featured_image_relative', 'created_at', 'updated_at'])
            ->where(['category' => 'Health', 'status' => 'Sedang Aktif'])
            ->orderBy(['id' => SORT_DESC])
            ->limit(30)
            ->offset(($page - 1) * 30)
            ->all();

        $lastPage = (function(){
            $query = new \yii\db\Query();
            $query
                ->select([
                    'count(*)',
                ])
                ->from('post p')
                ->where(['category' => 'Health', 'status' => 'Sedang Aktif'])
            ;
            $countPost = $query->scalar();

            return intdiv($countPost, 30) + ($countPost % 30 ? 1 : 0);
        })();

        return $this->render('list-post', [
            'title' => 'Health',
            'description' => 'All health tips',
            'model' => $model,
            'page' => $page,
            'lastPage' => $lastPage,
        ]);
    }
    
    public function actionDrug($page = 1)
    {
        $model['post'] = Post::find()->where(['category' => 'Health'])->limit(100)->offset($page*100)->orderBy(['title' => SORT_ASC])->all();

        return $this->render('list-az', [
            'title' => 'Drug',
            'description' => 'All drugs',
            'model' => $model,
        ]);
    }
}

views/layouts/main-starter.php
<?php

use app_starter\assets_manager\RequiredAsset;
use yii\helpers\Html;
use technosmart\yii\widgets\Menu as MenuWidget;
use yii\widgets\Breadcrumbs;
use technosmart\models\Menu;

RequiredAsset::register($this);
$this->beginPage();

if (Yii::$app->session->hasFlash('success'))
    $this->registerJs(
        'fn.alert("Success", "' . Yii::$app->session->getFlash('success') . '", "success");',
        3
    );
if (Yii::$app->session->hasFlash('info'))
    $this->registerJs(
        'fn.alert("Info", "' . Yii::$app->session->getFlash('info') . '", "info");',
        3
    );
if (Yii::$app->session->hasFlash('warning'))
    $this->registerJs(
        'fn.alert("Warning", "' . Yii::$app->session->getFlash('warning') . '", "warning");',
        3
    );
if (Yii::$app->session->hasFlash('error'))
    $this->registerJs(
        'fn.alert("Error", "' . Yii::$app->session->getFlash('error') . '", "danger");',
        3
    );
?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <title><?= $this->title ? strip_tags($this->title) . ' | ' : null ?><?= Yii::$app->params['app.name'] ?><?= Yii::$app->params['app.description'] ? ' - ' . Yii::$app->params['app.description'] : null ?></title>
        <meta name="description" content="<?= $this->description ? $this->description : Yii::$app->params['app.description'] ?>">
        <link rel="icon" href="<?= Yii::$app->getRequest()->getBaseUrl() ?>/img/favicon.ico">
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
        <meta name="viewport" content="device-width, height=device-height, initial-scale=1, minimum-scale=1">
        <meta name="base-url" content="<?= yii\helpers\Url::home(true) ?>">
        <?= Html::csrfMetaTags() ?>
        <?php $this->head() ?>
    </head>

    <body>
    <?php $this->beginBody() ?>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- START @ALERT & CONFIRM -->
        <div class="modal fade" id="modal-alert" tabindex="-1" role="dialog" aria-labelledby="title-alert">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="title-alert"></h4>
                    </div>
                    <div class="modal-body">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal-confirm" tabindex="-1" role="dialog" aria-labelledby="title-confirm">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="title-confirm"></h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default modal-yes" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-default modal-no" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /END @ALERT & CONFIRM -->

        <header class="header-wrapper border-bottom">
            <div class="header-left padding-y-10 padding-x-15">
                <span technoart-toggle=".has-sidebar-left" technoart-toggleclasses="toggle-left" class="margin-right-5 hidden-sm-greater">☰</span>
                <a href="<?= Yii::$app->urlManager->createUrl("site/index") ?>" class="underline-none">
                    <?= Yii::$app->params['app.name'] ?>
                </a>
            </div>
            <div class="header-right clearfix padding-y-10 padding-x-15">
                <?php if (!Yii::$app->user->isGuest) : ?>
                    <a class="pull-right m-pull-none" data-method="post" href="<?= Yii::$app->urlManager->createUrl("site/logout") ?>">Logout</a>
                <?php endif; ?>
            </div>
        </header>

        <main class="has-sidebar-left">
            <div class="overlay-left" technoart-toggle=".has-sidebar-left" technoart-toggleclasses="toggle-left"></div>

            <nav class="sidebar-left border-right padding-y-15">
                <?php $menuItem['main'] = [
                    [
                        'label' => 'Dev List',
                        'url' => ['dev/index'],
                        'visible' => Menu::menuVisible('dev', 'index'),
                    ],
                    [
                        'label' => 'Dev Create',
                        'url' => ['dev/create'],
                        'visible' => Menu::menuVisible('dev', 'create'),
                    ],
                ]; ?>
                <?php
                    $menu['main'] = MenuWidget::widget([
                        'items' => $menuItem['main'],
                        'options' => [
                            'class' => 'menu-y menu-xs menu-active-bold submenu-active-bold menu-active-bg-light-blue menu-hover-darker-10 submenu-active-bg-light-blue',
                        ],
                        'activateItems' => true,
                        'openParents' => true,
                        'parentsCssClass' => 'has-submenu',
                        'encodeLabels' => false,
                        'labelTemplate' => '<a>{label}</a>',
                        'hideEmptyItems' => true,
                    ]);
                ?>

                <?php if ($menu['main']): ?>
                    <?= $menu['main'] ?>
                    <hr class="margin-y-15">
                <?php endif; ?>
            </nav>

            <div class="page-wrapper padding-x-30 m-padding-x-10">
                <div class="border-bottom border-lighter padding-y-20 fw-light fs-16">
                    <?= Html::decode($this->title) ?>
                </div>

                <div class="padding-y-30">
                    <?= $content ?>
                </div>
            </div>
        </main>

        <footer class="border-top padding-y-15 text-center">
            <span class="fs-18 text-azure fs-italic"><?= Yii::$app->params['app.owner'] ?> © <?= date('Y') ?></span>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

use app_starter\assets_manager\RequiredAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use technosmart\yii\widgets\Menu as MenuWidget;
use yii\widgets\Breadcrumbs;
use technosmart\models\Menu;

RequiredAsset::register($this);
$this->beginPage();

if (Yii::$app->session->hasFlash('success'))
    $this->registerJs(
        'fn.alert("Success", "' . Yii::$app->session->getFlash('success') . '", "success");',
        3
    );
if (Yii::$app->session->hasFlash('info'))
    $this->registerJs(
        'fn.alert("Info", "' . Yii::$app->session->getFlash('info') . '", "info");',
        3
    );
if (Yii::$app->session->hasFlash('warning'))
    $this->registerJs(
        'fn.alert("Warning", "' . Yii::$app->session->getFlash('warning') . '", "warning");',
        3
    );
if (Yii::$app->session->hasFlash('error'))
    $this->registerJs(
        'fn.alert("Error", "' . Yii::$app->session->getFlash('error') . '", "danger");',
        3
    );
?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <?php if (YII_ENV == 'prod') : ?><!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156851132-2"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-156851132-2');
        </script>
        <?php endif; ?><title><?= $this->title ? strip_tags($this->title) . ' | ' : null ?><?= Yii::$app->params['app.name'] ?><?= Yii::$app->params['app.description'] ? ' - ' . Yii::$app->params['app.description'] : null ?></title>
        <meta name="description" content="<?= $this->description ? $this->description : Yii::$app->params['app.description'] ?>">
        <link rel="icon" href="<?= Yii::$app->getRequest()->getBaseUrl() ?>/img/favicon.ico">
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
        <meta name="viewport" content="device-width, height=device-height, initial-scale=1, minimum-scale=1">
        <meta name="base-url" content="<?= yii\helpers\Url::home(true) ?>">
        <?= Html::csrfMetaTags() ?>
        <?php $this->head() ?>
    </head>

    <body>
    <?php $this->beginBody() ?>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- START @ALERT & CONFIRM -->
        <div class="modal fade" id="modal-alert" tabindex="-1" role="dialog" aria-labelledby="title-alert">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="title-alert"></h4>
                    </div>
                    <div class="modal-body">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal-confirm" tabindex="-1" role="dialog" aria-labelledby="title-confirm">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="title-confirm"></h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default modal-yes" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-default modal-no" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /END @ALERT & CONFIRM -->

        <?php $menu['allMenu'] = [
            [
                'label' => 'HEALTH',
                'url' => ['post/health'],
            ],
            /*[
                'label' => 'Drugs',
                'url' => ['post/drug'],
            ],
            [
                'label' => 'Symptoms',
                'url' => ['site/index'],
            ],*/
        ]; ?>

        <header technoart-fixedonscroll="bg-lightest">
            <div class="hidden-sm-less">
                <div class="container border-bottom border-lighter border-thin">
                    <div class="pull-left padding-y-15">
                        <a href="<?= Yii::$app->urlManager->createUrl('site/index') ?>" class="a-nocolor">
                            <img src="<?= Yii::$app->getRequest()->getBaseUrl() ?>/img/logo-full.png" height="25px;" class="">
                        </a>
                    </div>

                    <nav>
                        <?= MenuWidget::widget([
                            'items' => $menu['allMenu'],
                            'options' => [
                                'class' => 'pull-right menu-x menu-space-y-15 menu-space-x-10 fs-14 text-gray
                                    menu-active-text-azure padding-y-5',
                            ],
                            'activateItems' => true,
                            'openParents' => true,
                            'parentsCssClass' => 'has-submenu',
                            'encodeLabels' => false,
                            'labelTemplate' => '<a>{label}</a>',
                            'hideEmptyItems' => true,
                        ]); ?>
                    </nav>
                </div>
            </div>
            <div class="visible-sm-less">
                <div class="text-center padding-y-10 bg-azure darker-20">
                    <a href="<?= Yii::$app->urlManager->createUrl('site/index') ?>" class="a-nocolor">
                        <img src="<?= Yii::$app->getRequest()->getBaseUrl() ?>/img/logo-full.png" height="30px;" class="bg-lightest padding-x-15 padding-y-5 rounded-lg">
                    </a>
                </div>
                <div class="bg-azure text-center">
                    <nav>
                        <?= MenuWidget::widget([
                            'items' => $menu['allMenu'],
                            'options' => [
                                'class' => 'menu-x menu-space-y-5 menu-space-x-10 fs-13 inline-block text-light-azure
                                    menu-active-text-lightest',
                            ],
                            'activateItems' => true,
                            'openParents' => true,
                            'parentsCssClass' => 'has-submenu',
                            'encodeLabels' => false,
                            'labelTemplate' => '<a>{label}</a>',
                            'hideEmptyItems' => true,
                        ]); ?>
                    </nav>
                </div>
            </div>
        </header>

        <main class="has-sidebar-left m-left">
            <div class="overlay-left" technoart-toggle=".has-sidebar-left" technoart-toggleclasses="toggle-left"></div>

            <nav class="sidebar-left border-right padding-y-15">
                <?php $menuItem['main'] = [
                    [
                        'label' => 'Dev List',
                        'url' => ['dev/index'],
                        'visible' => Menu::menuVisible('dev', 'index'),
                    ],
                    [
                        'label' => 'Dev Create',
                        'url' => ['dev/create'],
                        'visible' => Menu::menuVisible('dev', 'create'),
                    ],
                ]; ?>
                <?php
                    $menu['main'] = MenuWidget::widget([
                        'items' => $menuItem['main'],
                        'options' => [
                            'class' => 'menu-y menu-xs menu-active-bold submenu-active-bold menu-active-bg-light-blue menu-hover-darker-10 submenu-active-bg-light-blue',
                        ],
                        'activateItems' => true,
                        'openParents' => true,
                        'parentsCssClass' => 'has-submenu',
                        'encodeLabels' => false,
                        'labelTemplate' => '<a>{label}</a>',
                        'hideEmptyItems' => true,
                    ]);
                ?>

                <?php if ($menu['main']): ?>
                    <?= $menu['main'] ?>
                    <hr class="margin-y-15">
                <?php endif; ?>
            </nav>

            <div class="page-wrapper padding-x-30 m-padding-x-10">
                <?= $content ?>
                <div class="margin-top-30"></div>
            </div>
        </main>

        <footer>
            <div class="bg-darkest">
                <div class="container padding-y-30 m-text-center">
                  2018 - <?= date('Y'); ?> ©
                  <a href="<?= Url::to(['post/index', 't' => 'some-rights-reserved']) ?>" class="a-nocolor">Some Rights Reserved</a> |
                  <a href="<?= Url::to(['post/index', 't' => 'privacy-policy']) ?>" class="a-nocolor">Privacy Policy</a> |
                  <a href="<?= Url::to(['post/index', 't' => 'terms-of-service']) ?>" class="a-nocolor">Terms of Service</a> |
                  <a href="<?= Url::to(['post/index', 't' => 'contact-us']) ?>" class="a-nocolor">Contact Us</a>
                  <div class="pull-right m-pull-none m-margin-top-20 fs-italic">Clove Medical - We Care Your Health</div>
                </div>
              </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>